nombre = input("Ingrese su nombre acá: ")
edad = int(input("Ingrese su edad acá: "))
altura = float(input("Ingrese su altura acá: "))
print("=== FICHA PERSONAL ACTUALIZADA ===")
print("Nombre:",nombre)
print("Edad:",edad)
print("Altura:",altura)
print("En 10 años tendrás",edad+10,"años.")
print("Disfruta tu vida, ¡vive al máximo!")